/* Generated By:JavaCC: Do not edit this line. LibParserConstants.java */
package lib;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LibParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int LIBRARY = 2;
  /** RegularExpression Id. */
  int STRING_WITH_SPACES = 3;
  /** RegularExpression Id. */
  int STRING_WITH_SPACES_CAN_BE_EMPTY = 4;
  /** RegularExpression Id. */
  int WEBSITE_ENTRY = 5;
  /** RegularExpression Id. */
  int WEBSITE = 6;
  /** RegularExpression Id. */
  int BUILDING = 7;
  /** RegularExpression Id. */
  int BUILDING_NUMBER = 8;
  /** RegularExpression Id. */
  int TIME_OF_YEAR = 9;
  /** RegularExpression Id. */
  int DAY = 10;
  /** RegularExpression Id. */
  int MONTH = 11;
  /** RegularExpression Id. */
  int DAY_OF_MONTH = 12;
  /** RegularExpression Id. */
  int DAY_OF_WEEK = 13;
  /** RegularExpression Id. */
  int YEAR = 14;
  /** RegularExpression Id. */
  int START = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int HOURS = 17;
  /** RegularExpression Id. */
  int TIME = 18;
  /** RegularExpression Id. */
  int TO = 19;
  /** RegularExpression Id. */
  int CLOSED = 20;
  /** RegularExpression Id. */
  int STAFF = 21;
  /** RegularExpression Id. */
  int POSITION = 22;
  /** RegularExpression Id. */
  int EMAIL = 23;
  /** RegularExpression Id. */
  int TYPE = 24;
  /** RegularExpression Id. */
  int TYPE_VALUE = 25;
  /** RegularExpression Id. */
  int RATE = 26;
  /** RegularExpression Id. */
  int MONEY = 27;
  /** RegularExpression Id. */
  int DOLLAR = 28;
  /** RegularExpression Id. */
  int CENTS = 29;
  /** RegularExpression Id. */
  int BOOKCOLLECTION = 30;
  /** RegularExpression Id. */
  int BOOK = 31;
  /** RegularExpression Id. */
  int TITLE = 32;
  /** RegularExpression Id. */
  int BOOK_TITLE = 33;
  /** RegularExpression Id. */
  int AUTHOR = 34;
  /** RegularExpression Id. */
  int INITIAL = 35;
  /** RegularExpression Id. */
  int LB = 36;
  /** RegularExpression Id. */
  int RB = 37;
  /** RegularExpression Id. */
  int LP = 38;
  /** RegularExpression Id. */
  int RP = 39;
  /** RegularExpression Id. */
  int COLON = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int QUOTE = 42;
  /** RegularExpression Id. */
  int DOT = 43;
  /** RegularExpression Id. */
  int AT = 44;
  /** RegularExpression Id. */
  int AM_PM = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int CAPITAL_LETTER = 48;
  /** RegularExpression Id. */
  int DIGIT_OR_LETTER = 49;
  /** RegularExpression Id. */
  int DIGIT_OR_LETTER_OR_HYPHEN = 50;
  /** RegularExpression Id. */
  int BOOK_TITLE_CHAR = 51;
  /** RegularExpression Id. */
  int LETTER_OR_WHITESPACE = 52;
  /** RegularExpression Id. */
  int WEB_ADDRESS_CHAR = 53;
  /** RegularExpression Id. */
  int WEB_PREFIX = 54;
  /** RegularExpression Id. */
  int BOOK_ID = 55;
  /** RegularExpression Id. */
  int NAME_PART = 56;
  /** RegularExpression Id. */
  int PART = 57;
  /** RegularExpression Id. */
  int PART_WITH_HYPHEN = 58;
  /** RegularExpression Id. */
  int EMAIL_ADDRESS = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "\"LIBRARY\"",
    "<STRING_WITH_SPACES>",
    "<STRING_WITH_SPACES_CAN_BE_EMPTY>",
    "<WEBSITE_ENTRY>",
    "\"WEBSITE\"",
    "\"BUILDING\"",
    "<BUILDING_NUMBER>",
    "\"TIMEOFYEAR\"",
    "<DAY>",
    "<MONTH>",
    "<DAY_OF_MONTH>",
    "<DAY_OF_WEEK>",
    "<YEAR>",
    "\"START\"",
    "\"END\"",
    "\"HOURS\"",
    "<TIME>",
    "\"to\"",
    "\"CLOSED\"",
    "\"STAFF\"",
    "\"POSITION\"",
    "\"EMAIL\"",
    "\"TYPE\"",
    "<TYPE_VALUE>",
    "\"RATE\"",
    "<MONEY>",
    "<DOLLAR>",
    "<CENTS>",
    "\"BOOKCOLLECTION\"",
    "\"BOOK\"",
    "\"TITLE\"",
    "<BOOK_TITLE>",
    "\"AUTHOR\"",
    "<INITIAL>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
    "\"\\\"\"",
    "\".\"",
    "\"@\"",
    "<AM_PM>",
    "<DIGIT>",
    "<LETTER>",
    "<CAPITAL_LETTER>",
    "<DIGIT_OR_LETTER>",
    "<DIGIT_OR_LETTER_OR_HYPHEN>",
    "<BOOK_TITLE_CHAR>",
    "<LETTER_OR_WHITESPACE>",
    "<WEB_ADDRESS_CHAR>",
    "<WEB_PREFIX>",
    "<BOOK_ID>",
    "<NAME_PART>",
    "<PART>",
    "<PART_WITH_HYPHEN>",
    "<EMAIL_ADDRESS>",
  };

}
