/* Generated By:JavaCC: Do not edit this line. PersonParserConstants.java */
package names;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PersonParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int PERSON = 2;
  /** RegularExpression Id. */
  int LP = 3;
  /** RegularExpression Id. */
  int RP = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int LB = 6;
  /** RegularExpression Id. */
  int RB = 7;
  /** RegularExpression Id. */
  int SEMI = 8;
  /** RegularExpression Id. */
  int MISS = 9;
  /** RegularExpression Id. */
  int MRS = 10;
  /** RegularExpression Id. */
  int MS = 11;
  /** RegularExpression Id. */
  int DR = 12;
  /** RegularExpression Id. */
  int MADAM = 13;
  /** RegularExpression Id. */
  int MR = 14;
  /** RegularExpression Id. */
  int SIR = 15;
  /** RegularExpression Id. */
  int MALE = 16;
  /** RegularExpression Id. */
  int FEMALE = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int DIGIT_3 = 19;
  /** RegularExpression Id. */
  int PHONE_7 = 20;
  /** RegularExpression Id. */
  int PHONE_10 = 21;
  /** RegularExpression Id. */
  int NUMBER = 22;
  /** RegularExpression Id. */
  int LETTER = 23;
  /** RegularExpression Id. */
  int LETTER_OR_WHITESPACE = 24;
  /** RegularExpression Id. */
  int WORD = 25;
  /** RegularExpression Id. */
  int NAME = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "\"Person\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"Miss\"",
    "\"Mrs\"",
    "\"Ms\"",
    "\"Dr\"",
    "\"Madam\"",
    "\"Mr\"",
    "\"Sir\"",
    "\"M\"",
    "\"F\"",
    "<DIGIT>",
    "<DIGIT_3>",
    "<PHONE_7>",
    "<PHONE_10>",
    "<NUMBER>",
    "<LETTER>",
    "<LETTER_OR_WHITESPACE>",
    "<WORD>",
    "<NAME>",
  };

}
